name: Frontend CI/CD

on:
  push:
    branches:
      - main # Or your production branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

      - name: Verify build output
        run: ls -l ./dist

      - name: Copy build files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "./dist/"
          target: "/tmp/dist/"

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            sudo rm -rf /usr/share/nginx/html/*
            sudo cp -r /tmp/dist/* /usr/share/nginx/html/
            sudo chown -R www-data:www-data /usr/share/nginx/html
            sudo chmod -R 755 /usr/share/nginx/html
            sudo systemctl reload nginx
